<a href="https://colab.research.google.com/github/Towhid-Alam/Big-Data/blob/main/0_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ***NumPy***

***1.1 Creating Arrays***

In [ ]:
import numpy as np
towhid = np.array([3,6,5,5])
print(towhid)
print(type(towhid))

diu = np.array((3,6,5,5)) #Tuple used to create a numoy array
print(diu)

[3 6 5 5]
<class 'numpy.ndarray'>
[3 6 5 5]


***1.2 Dimensions in Arrays***

In [ ]:
d0 = np.array(3655) #0-D Array
print(d0)
print("\n")
d1 = np.array([3,6,5,5]) #1-D Array
print(d1)
print("\n")
d2 = np.array([[3,6,5,5],[3,6,5,5]]) #0-D Array
print(d2)
print("\n")

d3 = np.array([[[3,6,5,5],[3,6,5,5]],[[3,6,5,5],[3,6,5,5]]]) #0-D Array
print(d3)
print("\n")

d4 = np.array([[[[3,6,5,5],[3,6,5,5]],[[3,6,5,5],[3,6,5,5]]],[[[3,6,5,5],[3,6,5,5]],[[3,6,5,5],[3,6,5,5]]]]) #0-D Array
print(d4)
print("\n")


3655


[3 6 5 5]


[[3 6 5 5]
 [3 6 5 5]]


[[[3 6 5 5]
  [3 6 5 5]]

 [[3 6 5 5]
  [3 6 5 5]]]


[[[[3 6 5 5]
   [3 6 5 5]]

  [[3 6 5 5]
   [3 6 5 5]]]


 [[[3 6 5 5]
   [3 6 5 5]]

  [[3 6 5 5]
   [3 6 5 5]]]]




***1.3 Number of Dimensions***

In [ ]:
d0 = np.array(3655) #0-D Array
d1 = np.array([3,6,5,5]) #1-D Array
d2 = np.array([[3,6,5,5],[3,6,5,5]]) #0-D Array
d3 = np.array([[[3,6,5,5],[3,6,5,5]],[[3,6,5,5],[3,6,5,5]]]) #0-D Array
d4 = np.array([[[[3,6,5,5],[3,6,5,5]],[[3,6,5,5],[3,6,5,5]]],[[[3,6,5,5],[3,6,5,5]],[[3,6,5,5],[3,6,5,5]]]]) #0-D Array

print(d0.ndim)
print(d1.ndim)
print(d2.ndim)
print(d3.ndim)
print(d4.ndim)

0
1
2
3
4


***1.3 Defining Number of Dimensions***

In [ ]:
towhid = np.array([3,6,5,5], ndmin=5)
print(towhid)
print("Number of Dimensions =",towhid.ndim)

[[[[[3 6 5 5]]]]]
Number of Dimensions = 5


***2.1 Accessing Array Elements***

In [ ]:
towhid = np.array([3,6,5,5])
print(towhid[2])  #Third element output
print(towhid[2]+towhid[3])  #Addition of 3rd and 4th Elements

5
10


***2.2 Accessing 2D Arrays***

In [ ]:
towhid = np.array([[3,6,5,5],[7,8,9,10]])
print(towhid[1,2]) #Access 9

towhid = np.array([[3,6,5,5],[7,8,9,10]])
print(towhid[1,2],towhid[1,3]) #Access 9 and 10

9
9 10


***2.3 Accessing 3D Arrays***

In [ ]:
towhid = np.array([[[3,6,5,5],[7,8,9,10]],[[0,1,2,3],[4,11,12,13]]])
print(towhid[1,1,2]) #Access 12

towhid = np.array([[[3,6,5,5],[7,8,9,10]],[[0,1,2,3],[4,11,12,13]]])
print(towhid[1,0,1],towhid[1,1,3]) #Access 1 and 13

12
1 13


***2.4 Negative Indexing***

In [ ]:
towhid = np.array([[[3,6,5,5],[7,8,9,10]],[[0,1,2,3],[4,11,12,13]]])
print(towhid[1,1,-4]) #Access 4

4


***3.1 Slicing arrays***