<a href="https://colab.research.google.com/github/Towhid-Alam/Big-Data/blob/main/22_Autograd.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# The autograd package provides automatic gradient calculation.

In [2]:
import torch

In [3]:
input = torch.rand(1,3,64,64)
labels=torch.rand(1,1000)

In [4]:
from torchvision.models import resnet18, ResNet18_Weights
model= resnet18(weights=ResNet18_Weights.DEFAULT)
pred= model(input)

Downloading: "https://download.pytorch.org/models/resnet18-f37072fd.pth" to /root/.cache/torch/hub/checkpoints/resnet18-f37072fd.pth
100%|██████████| 44.7M/44.7M [00:00<00:00, 124MB/s] 


In [5]:
loss = (pred - labels).sum()
loss.backward()
optim= torch.optim.SGD(model.parameters(),lr=.001)
optim.step()

In [6]:
x = torch.rand(5)
y = torch.rand(5)
z = torch.rand((5), requires_grad=True)

In [7]:
a=x+y
a.requires_grad

False

In [8]:
b=x+z
b.requires_grad

True

In [9]:
c=x*z
c.requires_grad

True

In [10]:
a

tensor([0.9693, 1.0277, 0.6534, 0.8246, 0.9524])

In [11]:
b

tensor([0.8299, 1.2003, 0.9919, 0.4172, 1.1396], grad_fn=<AddBackward0>)

In [12]:
c

tensor([0.0069, 0.3526, 0.2097, 0.0050, 0.2990], grad_fn=<MulBackward0>)

In [13]:
c=c.mean()
c

tensor(0.1746, grad_fn=<MeanBackward0>)

In [14]:
z.grad

In [15]:
c.backward()
z.grad #gradient dc/dz

tensor([0.1643, 0.1375, 0.0611, 0.0809, 0.0819])

In [16]:
with torch.no_grad():
    print(z*2)

tensor([0.0168, 1.0257, 1.3727, 0.0249, 1.4601])


In [17]:
#D from scratch

In [18]:
x = torch.tensor(1.0)
y = torch.tensor(2.0)
w = torch.tensor(1.0, requires_grad=True) #parameter we want to optimi

In [19]:
w

tensor(1., requires_grad=True)

In [20]:
#Forward pass to compute loss
pred = w*x    #forward pass
loss = (pred - y)**2 #loss
#Backward pass to compute gradients using chain rule
loss.backward() #backward pass
w.grad # dloss/dw (partial derivatives)

tensor(-2.)

In [21]:
w.grad.zero_() #set gradient to zero

tensor(0.)

In [22]:
x= torch.tensor(3.)
w= torch.tensor(4., requires_grad=True)
b= torch.tensor(1., requires_grad=True)
x, w, b

(tensor(3.), tensor(4., requires_grad=True), tensor(1., requires_grad=True))

In [23]:
y = w * x + b

In [24]:
y

tensor(13., grad_fn=<AddBackward0>)

In [25]:
y.backward()

In [26]:
print(x.grad)

None


In [27]:
print(w.grad)

tensor(3.)


In [28]:
print(b.grad)

tensor(1.)
