<a href="https://colab.research.google.com/github/Towhid-Alam/Big-Data/blob/main/23_Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

In [2]:
data=[[1,2],[3,4]]
x_data= torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

In [3]:
arr=np.array(data)
arr

array([[1, 2],
       [3, 4]])

In [4]:
x=torch.from_numpy(arr)
x

tensor([[1, 2],
        [3, 4]])

In [5]:
x_ones= torch.ones_like(x)
x_ones

tensor([[1, 1],
        [1, 1]])

In [6]:
x_zeros= torch.zeros_like(x)
x_zeros

tensor([[0, 0],
        [0, 0]])

In [7]:
x_rand= torch.rand_like(x, dtype=torch.float)
x_rand

tensor([[0.5570, 0.3226],
        [0.9701, 0.0957]])

In [8]:
rand_tensor= torch.rand(2,3)
rand_tensor

tensor([[0.0074, 0.8965, 0.2029],
        [0.5121, 0.9988, 0.5204]])

In [9]:
ones_tensor= torch.ones(2,3, dtype=torch.float32)
ones_tensor

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [10]:
zeros_tensor= torch.zeros(2,3)
zeros_tensor

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [11]:
rand_tensor.shape

torch.Size([2, 3])

In [12]:
rand_tensor.dtype

torch.float32

In [13]:
rand_tensor.device

device(type='cpu')

In [14]:
if torch.cuda.is_available():
    rand_tensor = rand_tensor.to('cuda')

In [15]:
 rand_tensor

tensor([[0.0074, 0.8965, 0.2029],
        [0.5121, 0.9988, 0.5204]])

In [16]:
rand_tensor[:,1]=1
rand_tensor

tensor([[0.0074, 1.0000, 0.2029],
        [0.5121, 1.0000, 0.5204]])

In [17]:
rand_tensor[0]

tensor([0.0074, 1.0000, 0.2029])

In [19]:
rand_tensor[:,0]

tensor([0.0074, 0.5121])

In [18]:
rand_tensor[...,-1]

tensor([0.2029, 0.5204])

In [20]:
rand_tensor.sum()

tensor(3.2428)

In [21]:
rand_tensor.sum().item()

3.242771625518799

In [22]:
t1= torch.cat([rand_tensor, zeros_tensor],dim=1)
t1

tensor([[0.0074, 1.0000, 0.2029, 0.0000, 0.0000, 0.0000],
        [0.5121, 1.0000, 0.5204, 0.0000, 0.0000, 0.0000]])

In [23]:
t2= torch.cat([rand_tensor, zeros_tensor],dim=0)
t2

tensor([[0.0074, 1.0000, 0.2029],
        [0.5121, 1.0000, 0.5204],
        [0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000]])

In [24]:
rand_tensor.mul(ones_tensor)

tensor([[0.0074, 1.0000, 0.2029],
        [0.5121, 1.0000, 0.5204]])

In [25]:
rand_tensor.matmul(rand_tensor.T)

tensor([[1.0412, 1.1094],
        [1.1094, 1.5330]])

In [26]:
rand_tensor.add_(5)

tensor([[5.0074, 6.0000, 5.2029],
        [5.5121, 6.0000, 5.5204]])

In [27]:
n= np.ones(5)
n

array([1., 1., 1., 1., 1.])

In [28]:
t=torch.from_numpy(n)
t

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)

In [29]:
t.add_(1)

tensor([2., 2., 2., 2., 2.], dtype=torch.float64)

In [30]:
x = torch.empty(1)
print(x)

tensor([-42153344.])


In [31]:
x.size()

torch.Size([1])

In [32]:
x = torch.empty(2,3)
print(x)

tensor([[2.6038e-05, 3.3131e-41, 2.1483e-02],
        [3.3131e-41, 8.9683e-44, 0.0000e+00]])


In [33]:
torch.empty(2,2,3)

tensor([[[ 2.6042e-05,  3.3131e-41,  2.1463e-02],
         [ 3.3131e-41,  4.4842e-43,  0.0000e+00]],

        [[ 1.5695e-43,  0.0000e+00, -5.0825e+34],
         [ 3.3135e-41,  5.6052e-44,  7.4269e-44]]])

In [34]:
y=x.view(6)
y

tensor([2.6038e-05, 3.3131e-41, 2.1483e-02, 3.3131e-41, 8.9683e-44, 0.0000e+00])

In [35]:
z=x.view(1,-1)
z

tensor([[2.6038e-05, 3.3131e-41, 2.1483e-02, 3.3131e-41, 8.9683e-44, 0.0000e+00]])

In [36]:
a= torch.ones(2,2)
b= torch.ones(2,2)
a,b

(tensor([[1., 1.],
         [1., 1.]]),
 tensor([[1., 1.],
         [1., 1.]]))

In [37]:
a+b

tensor([[2., 2.],
        [2., 2.]])

In [38]:
a-b

tensor([[0., 0.],
        [0., 0.]])

In [39]:
a*b

tensor([[1., 1.],
        [1., 1.]])

In [40]:
a/b

tensor([[1., 1.],
        [1., 1.]])

In [41]:
a[1,1].item()

1.0

In [42]:
torch.full((2,3),50)

tensor([[50, 50, 50],
        [50, 50, 50]])